AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Example bucket
